version: "1.0"
info:
  model: int-scaffold
packages:
- name: DevSSAProject
  gitServerName: LATAMDev
  gitUrl: https://github.com/llara-la
  gitUsername: llara-la
  gitBranch: main
services:
- serviceName: project.devssa.integrations:DbGetDatos
  packages:
  - name: DevSSAProject
    version: "1.0"
